### ISSUE TITLE
Why making onWithdrawal `external`?

### ISSUE THREAD

**Issue by janus** [thxprotocol/wallet-contracts#14]

**Comment by peterpolman** [comment]
You've got a fair point there my friend. Thanks for taking the time and look at the code. I dove into the history and realised that this part got unprotected when the withdrawal was extracted from the logic that finalises the withdraw poll. I'll provide a fix for this right away.

**Comment by janus** [comment]
@peterpolman  I came here because of your gitcoin bounty but is like you have approved someone and that means I can't continue reviewing the code. Am I correct?

**Comment by peterpolman** [comment]
Yes indeed, we are working with @Evert0x on the review. Stay tuned though! We will post a more elaborate bounty program when we move to the next version.

**Comment by janus** [comment]
It won't be strange if I am tipped to compensate for the gas I have expended....
