### ISSUE TITLE
Change state changing methods to accept signed params 

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/wallet-contracts#23]
As done for `BasePoll.vote()` and `BasePool.revokeVote()` methods.

**Comment by Evert0x** [comment]
These methods include

~~[ ] AssetPool.deposit()~~
[x] AssetPool.claimWithdraw()
[x] AssetPool.updateReward()
[x] AssetPool.proposeWithdraw()
[x] WithdrawPoll.withdraw()
[x] BasePoll.vote()
[x] BasePoll.revokeVote()

After a private discussion decided to remove the deposit function and manage balances by direct erc20 transfer functions to the pool.

**Comment by Evert0x** [comment]
I think `AssetPool.proposeWithdraw()` is missing, right?

**Comment by peterpolman** [comment]
Yes, also the addMember and removeMember methods are missing. Or is that on purpose? I have a list of API methods to implement here, probably aligns with what needs to happen on the contract side:)

https://github.com/thxprotocol/api/issues/19
