### ISSUE TITLE
Protect methods with manager role

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/wallet-contracts#25]
These methods can only be used by MANAGER_ROLE roles. This doesn't affect the current scenario where only the admin can invoked them

AssetPool
- [x] addManager
- [x] removeManager
- [x] addMember
- [x] removeMember
- [x] setRewardPollDuration
- [x] setProposeWithdrawPollDuration

WithdrawPoll
- [x] vote
- [x] revokeVote
- [x] tryToFinalize

**Comment by Evert0x** [comment]
@ The last segment 


`vote`, `revokeVote` can only be called by our GasStation, these methods check if the signer is a member and qualified to call the method

`tryToFinalize` can be called by everyone, and I don't think this is a bad design.

**Comment by Evert0x** [comment]
@peterpolman, do you agree with the statement above? If yes, you can close this issue.

**Comment by peterpolman** [comment]
@Evert0x Not entirely: 

*  `WithdrawPoll.vote()` and `WithdrawPoll.revokeVote()` should only be allowed for manager roles. Since they should be able to control the flow of assets out of the pool (as a security mechanism) and not the members themselves. 
* The current design for `tryToFinalize` will indeed suffice.

**Comment by Evert0x** [comment]
The following logic is implemented

`WithdrawPoll.vote()` & `WithdrawPoll.revokeVote()` is **manager** only 
`RewardPoll.vote()` & `RewardPoll.revokeVote()` is **member** only _(the manager is also a member)_

@peterpolman can you verify the logic? And close ticket if okay.

**Comment by peterpolman** [comment]
Seems like a valid implementation! Closing the ticket.
