### ISSUE TITLE
Admin should be able to give a withdraw to a reward beneficiary

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/wallet-contracts#29]
Similar to `claimWithdraw` but will not use `_msgSender` as the beneficiary but a new parameter: `withdrawBeneficiary`. This method should be protected with `onlyAdmin` and enabled API consumers to give rewards to users without requiring them to sign a transaction since the admin will do this. `withdrawBeneficiary` should have the MEMBER_ROLE.

**Comment by Evert0x** [comment]
Some naming changes

`claimWithdraw` --> `claimReward`
`claimRewardFor`, the functionality described.

Both these function will start a `withdrawPoll`

**Comment by Evert0x** [comment]
Branch `/feature/26` contains this.

**Comment by peterpolman** [comment]
@Evert0x This one still needs some tests I presume? 

1. We can move that to the scope of #11 and close this issue or 
2. We leave this one open so we can link the future PR to it and close it once it is reviewed

Lemme know!

**Comment by Evert0x** [comment]
It still needs tests and it is part of the refactor. 

I prefer to close this one and include it in #11
