### ISSUE TITLE
Withdraw simplification

### ISSUE THREAD

**Issue by Evert0x** [thxprotocol/wallet-contracts#30]
Current flow
- withdrawpoll
- ~ voting process
- tryToFinalize
- withdraw

`Withdraw` should call `tryToFinalize` if the state is `Pending`, this will reduce the flow to

- withdrawpoll
- ~ voting process
- withdraw

**Comment by peterpolman** [comment]
@Evert0x This commit got merged into develop together with the open Buidler PR. Can we close this ticket or will it require more work and a new PR?

**Comment by Evert0x** [comment]
I will close this ticket.
