### ISSUE TITLE
Duplicate basepoll view methods

### ISSUE THREAD

**Issue by Evert0x** [thxprotocol/wallet-contracts#31]
The following snippet contains duplicate view methods

I propose to create a single one, named: `getCurrentApprovalState`

https://github.com/thxprotocol/contracts/blob/bb853b0eed3d8362161825cb6846dcbda3d39209/contracts/poll/BasePoll.sol#L175;L182

**Comment by peterpolman** [comment]
Proposal accepted!🦾
