### ISSUE TITLE
Bypass rewardPoll when rewardPollDuration is 0 

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/wallet-contracts#36]
AssetPool.addReward:
If `AssetPool.rewardPollDuration ===  0`, do not start a poll and enable the reward immediately.

AssetPool.updateReward:
If `AssetPool.rewardPollDuration ===  0`, do not start a poll and set the new values immediately.

**Comment by Evert0x** [comment]
Made me realize these lines can not co exist

https://github.com/thxprotocol/contracts/blob/develop/contracts/poll/BasePoll.sol#L60 
https://github.com/thxprotocol/contracts/blob/develop/contracts/poll/BasePoll.sol#L68
